site_name: CLIMB-TRE
site_url: https://climb-tre.github.io/
repo_url: https://github.com/CLIMB-TRE/climb-tre.github.io/
site_author: CLIMB-TRE team
theme:
  name: material

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            show_source: false
  - with-pdf:
      output_path: climb-tre.pdf
      cover_subtitle: ""

nav:
  - Home: index.md
  - Onyx Client Installation Guide: onyx_client_installation_guide.md
