site_name: CLIMB-TRE
site_url: https://climb-tre.github.io/
repo_url: https://github.com/CLIMB-TRE/climb-tre.github.io/
site_author: CLIMB-TRE team
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            show_source: false
  - with-pdf:
      output_path: climb-tre.pdf
      cover_subtitle: ""
      debug_html: true
      show_anchors: true
      verbose: true

nav:
  - Home: index.md
  - Getting started:
    - Uploading data: upload.md
    - Analysing data: analyse.md
  - Project specs:
    - Common structure: common.md
    - PATH-SAFE: pathsafe.md
    - mSCAPE: mscape.md
  - Onyx Documentation: https://CLIMB-TRE.github.io/onyx-client/
