site_name: CLIMB-TRE
theme:
  name: material

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            show_source: false
  - with-pdf

nav:
  - Home: index.md
